import type { DocKind, Gig } from "@/lib/types";

const t = Date.UTC(2026, 7, 1);

export const DEMO_GIGS: Gig[] = [
  {
    id: "gig-maja-ivan",
    title: "Maja & Ivan",
    type: "svadba",
    date: "2026-08-15",
    startTime: "18:00",
    endTime: "02:00",
    venue: "Restoran Panorama",
    city: "Zagreb",
    address: "Sljemenska cesta 4",
    contactName: "Ivan Babić",
    contactPhone: "+385 91 200 1100",
    fee: 1800,
    deposit: 500,
    status: "odradeno",
    notes: "Ceremonija na terasi u 18:30. Mladi su tražili tiši prvi sat, pa puni ples od 21:00.",
    setlist: "Klasični prvi ples: Perfect — Ed Sheeran\nDalmatina, starogradske, disco od ponoći.",
    createdAt: t,
  },
  {
    id: "gig-petra-tomislav",
    title: "Petra & Tomislav",
    type: "svadba",
    date: "2026-08-29",
    startTime: "17:30",
    endTime: "01:30",
    venue: "Hotel Palace",
    city: "Opatija",
    address: "Maršala Tita 108",
    contactName: "Petra Kovač",
    contactPhone: "+385 98 441 221",
    fee: 2200,
    deposit: 700,
    status: "odradeno",
    notes: "Malo akustično slavlje u salonu, pa velika dvorana. Clavinova je na pozornici.",
    setlist: "Prvi ples: At Last\nJazz standardi, onda zabava.",
    createdAt: t,
  },
  {
    id: "gig-spaladium",
    title: "Ljetni korporativ — Adriatica",
    type: "korporativ",
    date: "2026-09-05",
    startTime: "20:00",
    endTime: "00:30",
    venue: "Spaladium Arena lounge",
    city: "Split",
    address: "Zrinsko-Frankopanska 211",
    contactName: "Martina Vuković",
    contactPhone: "+385 21 555 019",
    fee: 1500,
    deposit: 400,
    status: "odradeno",
    notes: "Pozadinska glazba za networking, pa 45 min show set.",
    setlist: "Lounge 20:00–22:00, show 22:15.",
    createdAt: t,
  },
  {
    id: "gig-lucija-filip",
    title: "Lucija & Filip",
    type: "svadba",
    date: "2026-09-12",
    startTime: "18:00",
    endTime: "02:00",
    venue: "Vila Elera",
    city: "Zagreb",
    address: "Gornje Prekrižje 12",
    contactName: "Filip Horvat",
    contactPhone: "+385 91 777 0102",
    fee: 2000,
    deposit: 600,
    status: "odradeno",
    notes: "Kišni plan: dvorana umjesto vrta. Ozvučenje kuće je dovoljno.",
    setlist: "Prvi ples: Thinking Out Loud",
    createdAt: t,
  },
  {
    id: "gig-ana-marko",
    title: "Ana & Marko",
    type: "svadba",
    date: "2026-09-19",
    startTime: "18:00",
    endTime: "02:00",
    venue: "Restoran Dvorac",
    city: "Bedekovčina",
    address: "Trakošćanska 1",
    contactName: "Marko Jurić",
    contactPhone: "+385 95 333 4411",
    fee: 2500,
    deposit: 800,
    status: "potvrdeno",
    notes:
      "Dolazak u 16:30 za soundcheck. Ceremonija u parku dvorca 17:45. Večera u velikoj sali, ples od 21:30. Parking iza kuhinje.",
    setlist:
      "Ulazak: Canon in D (kvartet + vokal)\nPrvi ples: La vie en rose\nStarogradske, dalmatina, 80s/90s, after od 00:30.",
    createdAt: t,
  },
  {
    id: "gig-iva-luka",
    title: "Iva & Luka",
    type: "svadba",
    date: "2026-09-26",
    startTime: "19:00",
    endTime: "03:00",
    venue: "Villa Magnolia",
    city: "Split",
    address: "Šetalište Marina 8",
    contactName: "Iva Radić",
    contactPhone: "+385 91 612 8800",
    fee: 2300,
    deposit: 700,
    status: "potvrdeno",
    notes: "Open-air terasa do 23:00, zatim zimski vrt. Traže klape i moderni pop.",
    setlist: "Prvi ples: Rewrite the Stars\nKlape, then party.",
    createdAt: t,
  },
  {
    id: "gig-kovac-krstenje",
    title: "Krštenje obitelj Kovač",
    type: "krstenje",
    date: "2026-10-03",
    startTime: "13:00",
    endTime: "17:00",
    venue: "Restoran Vinodol",
    city: "Zagreb",
    address: "Nikole Tesle 10",
    contactName: "Ana Kovač",
    contactPhone: "+385 1 481 339",
    fee: 800,
    deposit: 200,
    status: "potvrdeno",
    notes: "Akustični trio. Crkva sv. Marka u 11:30 — samo orgulje, mi sviramo na slavlju.",
    setlist: "Lagani jazz, starogradske, dječje pjesme 20 min.",
    createdAt: t,
  },
  {
    id: "gig-esplanade",
    title: "20 godina tvrtke Norda",
    type: "korporativ",
    date: "2026-10-10",
    startTime: "19:30",
    endTime: "23:30",
    venue: "Hotel Esplanade",
    city: "Zagreb",
    address: "Mihanovićeva 1",
    contactName: "Ivana Šimić",
    contactPhone: "+385 1 456 1919",
    fee: 1800,
    deposit: 500,
    status: "upit",
    notes: "Još čekamo potvrdu setliste od marketinga. Dress code: black tie.",
    setlist: "Swing i bossa, bez vokala u prvom satu.",
    createdAt: t,
  },
  {
    id: "gig-petra-josip",
    title: "Petra & Josip",
    type: "svadba",
    date: "2026-10-17",
    startTime: "18:00",
    endTime: "02:00",
    venue: "Restoran Dubravkin put",
    city: "Zagreb",
    address: "Dubravkin put 2",
    contactName: "Josip Novak",
    contactPhone: "+385 98 200 331",
    fee: 2100,
    deposit: 600,
    status: "potvrdeno",
    notes: "Mali prostor — akustika pažljivo. Max 6 na pozornici.",
    setlist: "Prvi ples: Can't Help Falling in Love",
    createdAt: t,
  },
  {
    id: "gig-roden-50",
    title: "50. rođendan — g. Babić",
    type: "privatna",
    date: "2026-10-24",
    startTime: "19:00",
    endTime: "00:00",
    venue: "Konoba Didov san",
    city: "Zagreb",
    address: "Mletačka 11",
    contactName: "Lana Babić",
    contactPhone: "+385 91 555 0198",
    fee: 1200,
    deposit: 300,
    status: "upit",
    notes: "Žele starogradske i narodnjake, bez preglasnog bubnja.",
    setlist: "Tamburaški set + vokal.",
    createdAt: t,
  },
  {
    id: "gig-elena-nikola",
    title: "Elena & Nikola",
    type: "svadba",
    date: "2026-11-07",
    startTime: "17:00",
    endTime: "01:00",
    venue: "Hotel Ambasador",
    city: "Opatija",
    address: "F. Supila 19",
    contactName: "Nikola Marić",
    contactPhone: "+385 51 710 444",
    fee: 2600,
    deposit: 900,
    status: "potvrdeno",
    notes: "Dva seta: cocktail na terasi i večera u Crystal hall.",
    setlist: "Prvi ples: Fly Me to the Moon",
    createdAt: t,
  },
  {
    id: "gig-zkm",
    title: "Večer dalmatinskih pjesama",
    type: "koncert",
    date: "2026-11-21",
    startTime: "20:00",
    endTime: "22:30",
    venue: "ZKM — dvorana",
    city: "Zagreb",
    address: "Trg žrtava fašizma 10",
    contactName: "Tehnička produkcija ZKM",
    contactPhone: "+385 1 461 0777",
    fee: 900,
    deposit: 0,
    status: "potvrdeno",
    notes: "Kućno ozvučenje. Soundcheck 17:00. Dress: tamno, bez sjaja.",
    setlist: "Klape aranžmani, 90 minuta bez pauze.",
    createdAt: t,
  },
  {
    id: "gig-sara-mateo",
    title: "Sara & Mateo",
    type: "svadba",
    date: "2026-12-12",
    startTime: "18:30",
    endTime: "02:00",
    venue: "Dvorac Samobor",
    city: "Samobor",
    address: "Giznik 1",
    contactName: "Sara Vuk",
    contactPhone: "+385 91 404 2288",
    fee: 2400,
    deposit: 800,
    status: "upit",
    notes: "Zimska svadba, kamin u sali. Potvrda do 1. studenoga.",
    setlist: "Prvi ples: All of Me",
    createdAt: t,
  },
  {
    id: "gig-newyear",
    title: "Novogodišnji ball",
    type: "korporativ",
    date: "2026-12-31",
    startTime: "21:00",
    endTime: "03:00",
    venue: "Hotel Westin",
    city: "Zagreb",
    address: "Kršnjavoga 1",
    contactName: "Events desk Westin",
    contactPhone: "+385 1 682 2000",
    fee: 3200,
    deposit: 1200,
    status: "potvrdeno",
    notes: "Countdown set 23:50. Midnight: Auld Lang Syne pa disco. Extra naknada za after 03:00.",
    setlist: "Swing, disco, pop hits, midnight anthem.",
    createdAt: t,
  },
];

export type DemoDocSpec = {
  id: string;
  filename: string;
  kind: DocKind;
  title: string;
  lines: string[];
};

export function demoDocumentsFor(gig: Gig): DemoDocSpec[] {
  if (gig.id === "gig-ana-marko") {
    return [
      {
        id: "doc-ana-ugovor",
        filename: "Ugovor-Ana-Marko.pdf",
        kind: "ugovor",
        title: "Ugovor o nastupu",
        lines: [
          "Kapela  /  knjiga nastupa",
          "",
          "Narucitelj: Ana Petrovic i Marko Juric",
          "Datum: 19. rujna 2026.",
          "Mjesto: Restoran Dvorac, Bedekovcina",
          "Vrijeme: 18:00 - 02:00",
          "Naknada: 2.500 EUR  /  predujam 800 EUR",
          "",
          "Sastav: vokal, klavijature, gitara, bas, bubanj, sax.",
          "Dolazak za soundcheck: 16:30.",
          "",
          "Potpisi: ________________      ________________",
        ],
      },
      {
        id: "doc-ana-predracun",
        filename: "Predracun-Ana-Marko.pdf",
        kind: "predracun",
        title: "Predracun br. 2026-0919",
        lines: [
          "Kapela",
          "",
          "Za: svadba Ana i Marko",
          "Nastup 19.09.2026. Restoran Dvorac",
          "",
          "Honorari benda                  2.200 EUR",
          "Prijevoz i smjestaj               300 EUR",
          "Ukupno                          2.500 EUR",
          "Predujam (placen)                 800 EUR",
          "Za platiti do 12.09.            1.700 EUR",
        ],
      },
      {
        id: "doc-ana-setlista",
        filename: "Setlista-Ana-Marko.pdf",
        kind: "setlista",
        title: "Setlista — Ana i Marko",
        lines: [
          "Ceremonija",
          "  Canon in D   /   A Thousand Years",
          "",
          "Prvi ples",
          "  La vie en rose",
          "",
          "Vecera (pozadina)",
          "  jazz standardi, bossa, chanson",
          "",
          "Ples 21:30",
          "  Starogradske, Dalmatina, 80s, 90s",
          "After 00:30  —  disco i zahtjevi gostiju",
        ],
      },
    ];
  }
  if (gig.id === "gig-iva-luka") {
    return [
      {
        id: "doc-iva-ugovor",
        filename: "Ugovor-Iva-Luka.pdf",
        kind: "ugovor",
        title: "Ugovor o nastupu",
        lines: [
          "Narucitelj: Iva Radic i Luka Peric",
          "Datum: 26. rujna 2026.",
          "Mjesto: Villa Magnolia, Split",
          "Naknada: 2.300 EUR",
        ],
      },
      {
        id: "doc-iva-rider",
        filename: "Rider-Villa-Magnolia.pdf",
        kind: "rider",
        title: "Tehnicki rider",
        lines: [
          "Pozornica min. 4 x 3 m",
          "Napajanje 2 x 16A, odvojeno od rasvjete",
          "Monitori: 3 puta",
          "Open-air do 23:00, zatim zimski vrt",
        ],
      },
    ];
  }
  if (gig.id === "gig-lucija-filip") {
    return [
      {
        id: "doc-lucija-racun",
        filename: "Racun-Lucija-Filip.pdf",
        kind: "racun",
        title: "Racun br. 2026-0912",
        lines: [
          "Svadba Lucija i Filip",
          "Vila Elera, 12. rujna 2026.",
          "Iznos: 2.000 EUR — placeno u cijelosti.",
        ],
      },
    ];
  }
  if (gig.id === "gig-newyear") {
    return [
      {
        id: "doc-ny-ugovor",
        filename: "Ugovor-Westin-NYE.pdf",
        kind: "ugovor",
        title: "Ugovor — Novogodisnji ball",
        lines: [
          "Hotel Westin, Zagreb",
          "31. prosinca 2026.  21:00 - 03:00",
          "Naknada 3.200 EUR, predujam 1.200 EUR",
          "Countdown set obavezan u 23:50.",
        ],
      },
    ];
  }
  return [];
}
